# Stating version number of docker
version: "3"
services:
# Services is referred to containers
  redis-server:
    image: redis
  node-app:
  # Build the node app with the docker file from the current directory
    build: .
    # Designate Port Mapping
    ports:
      - "4001:8081"